apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acg-front-end.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "acg-front-end.name" . }}
    chart: {{ include "acg-front-end.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "acg-front-end.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "acg-front-end.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ include "acg-front-end.fullname" . }}-config-file
          secret:
            secretName: {{ include "acg-front-end.fullname" . }}-config-file
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: {{ template "acg-front-end.fullname" . }}-config-file
              mountPath: /usr/share/nginx/html/assets/json/config.json
              subPath: config.json   
