apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.metadata.labels.app }}
    chart: {{ .Values.metadata.labels.chart }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{  .Values.spec.volumes.name }}-config-file
          secret:
            secretName: {{ .Values.spec.volumes.name  }}-config-file
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.spec.volumes.name }}-config-file
              mountPath: /usr/share/nginx/html/assets/json/config.json
              subPath: config.json
