apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}-config-file
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  config.json: {{ tpl (.Files.Get "config.json.tpl") . | b64enc | quote }}