apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "acg-front-end.name" . }}
    chart: {{ include "acg-front-end.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "acg-front-end.name" . }}
    release: {{ .Release.Name }}
