apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{  .Values.metadata.labels.app }}
    chart: {{ .Values.metadata.labels.chart }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.metadata.labels.app }}
    release: {{ .Release.Name }}
